*** empty log message ***

diff --git a/bin/jmax b/bin/jmax
--- a/bin/jmax
+++ b/bin/jmax
@@ -30,7 +30,7 @@
 # JAVA_DEFAULT_OPTIONS="-noclassgc -noasyncgc -mx64m -ms2m"
 JAVA_DEFAULT_OPTIONS="-noclassgc -mx64m -ms2m"
 
-prefix=/u.livorno/worksta/borghesi/jmax
+prefix=/u/worksta/borghesi/projects/jmax-install
 exec_prefix=${prefix}
 rootdir=${prefix}/share/jmax
 ftsdir=${exec_prefix}/bin
@@ -46,7 +46,6 @@ help ()
 Usage:
     jmax [-javaopt <java-option>]
 	    [-nofork]
-	    [-nojar]
 	    [-root|-r <directory>]
 	    [-verbose] [<other-jmax-options>]
 
@@ -62,11 +61,6 @@ Options and arguments:
   -nofork
     Do not go into the background.  By default, jMax forks itself to give control 
     back to the shell.
-
-  -nojar
-    Do not use the jMax Java classes in JAR file jmax.jar. Use the .class files
-    in their package directories instead.
-    By default, jMax uses the jMax Java classes in JAR file jmax.jar
 
   -root|-r <directory>       (optional)
     Specify the root directory (where to find the jmax.jar file, the initialization
@@ -100,7 +94,6 @@ decrypt_options ()
     JMAXOPT=""
     VERBOSE=
     NOFORK=
-    NOJAR=
     ROOTDIR=$rootdir
 
     for arg in $@
@@ -117,8 +110,6 @@ decrypt_options ()
 		VERBOSE="yes" ;;
 	    \-nofork)
 		NOFORK="yes" ;;
-	    \-nojar)
-		NOJAR="yes" ;;
 	    \-root | \-r)
 		opt=$arg ;;
 	    *)
@@ -141,39 +132,25 @@ decrypt_options ()
 # ---------------------------------------------------------------------------
 check_installation ()
 {
-    if [ $NOJAR ]
+    if [ ! -f ${javadir}/jmax.jar ]
     then
-	if [ ! -f ${javadir}/src/ircam/jmax/MaxApplication.class ]
-	then
-	    echo "Cannot find file ${javadir}/src/ircam/jmax/MaxApplication.class"
-	    echo "You have probably installed a source distribution and did not compile it !"
-	    exit 1
-	fi
-    else
-	if [ ! -f ${javadir}/jmax.jar ]
-	then
-	    echo "Cannot find file ${javadir}/jmax.jar"
-	    echo "You have probably installed a source distribution and did not compile it !"
-	    exit 1
-	fi
+        echo "Cannot find file ${javadir}/jmax.jar"
+	echo "You have probably installed a source distribution and did not compile it !"
+	exit 1
     fi
-}
+ }
 
 # ---------------------------------------------------------------------------
 build_classpath ()
 {
-    if [ $NOJAR ]
-    then
-	JMAX_CLASSPATH=${javadir}/src
-    else
-	JMAX_CLASSPATH=${javadir}/jmax.jar
-    fi
+    JMAX_CLASSPATH=${javadir}/jmax.jar:${rootdir}/client/java/ftsclient.jar
 
+    INTERP_CLASSPATH=${javadir}/lib/jacl/jacl.jar:${javadir}/lib/jacl/tcljava.jar
     if [ $CLASSPATH ]
     then
-	CLASSPATH=${CLASSPATH}:${JMAX_CLASSPATH}:${javadir}/jacl.jar:${javadir}/tcljava.jar
+	CLASSPATH=${CLASSPATH}:${JMAX_CLASSPATH}:${INTERP_CLASSPATH}
     else
-	CLASSPATH=${JMAX_CLASSPATH}:${javadir}/jacl.jar:${javadir}/tcljava.jar
+	CLASSPATH=${JMAX_CLASSPATH}:${INTERP_CLASSPATH}
     fi
 }
 
diff --git a/bin/jmax.in b/bin/jmax.in
--- a/bin/jmax.in
+++ b/bin/jmax.in
@@ -46,7 +46,6 @@ help ()
 Usage:
     jmax [-javaopt <java-option>]
 	    [-nofork]
-	    [-nojar]
 	    [-root|-r <directory>]
 	    [-verbose] [<other-jmax-options>]
 
@@ -62,11 +61,6 @@ Options and arguments:
   -nofork
     Do not go into the background.  By default, jMax forks itself to give control 
     back to the shell.
-
-  -nojar
-    Do not use the jMax Java classes in JAR file jmax.jar. Use the .class files
-    in their package directories instead.
-    By default, jMax uses the jMax Java classes in JAR file jmax.jar
 
   -root|-r <directory>       (optional)
     Specify the root directory (where to find the jmax.jar file, the initialization
@@ -100,7 +94,6 @@ decrypt_options ()
     JMAXOPT=""
     VERBOSE=
     NOFORK=
-    NOJAR=
     ROOTDIR=$rootdir
 
     for arg in $@
@@ -117,8 +110,6 @@ decrypt_options ()
 		VERBOSE="yes" ;;
 	    \-nofork)
 		NOFORK="yes" ;;
-	    \-nojar)
-		NOJAR="yes" ;;
 	    \-root | \-r)
 		opt=$arg ;;
 	    *)
@@ -141,33 +132,18 @@ decrypt_options ()
 # ---------------------------------------------------------------------------
 check_installation ()
 {
-    if [ $NOJAR ]
+    if [ ! -f ${javadir}/jmax.jar ]
     then
-	if [ ! -f ${javadir}/src/ircam/jmax/MaxApplication.class ]
-	then
-	    echo "Cannot find file ${javadir}/src/ircam/jmax/MaxApplication.class"
-	    echo "You have probably installed a source distribution and did not compile it !"
-	    exit 1
-	fi
-    else
-	if [ ! -f ${javadir}/jmax.jar ]
-	then
-	    echo "Cannot find file ${javadir}/jmax.jar"
-	    echo "You have probably installed a source distribution and did not compile it !"
-	    exit 1
-	fi
+        echo "Cannot find file ${javadir}/jmax.jar"
+	echo "You have probably installed a source distribution and did not compile it !"
+	exit 1
     fi
-}
+ }
 
 # ---------------------------------------------------------------------------
 build_classpath ()
 {
-    if [ $NOJAR ]
-    then
-	JMAX_CLASSPATH=${javadir}/src
-    else
-	JMAX_CLASSPATH=${javadir}/jmax.jar
-    fi
+    JMAX_CLASSPATH=${javadir}/jmax.jar:${rootdir}/client/java/ftsclient.jar
 
     INTERP_CLASSPATH=${javadir}/lib/jacl/jacl.jar:${javadir}/lib/jacl/tcljava.jar
     if [ $CLASSPATH ]
