Fixed some chmod().

diff --git a/bin/jmax-tar-distrib b/bin/jmax-tar-distrib
--- a/bin/jmax-tar-distrib
+++ b/bin/jmax-tar-distrib
@@ -1,4 +1,15 @@
 #!/bin/sh
+
+# ***************************************************************************
+# Constants
+# ***************************************************************************
+RELEASES_DIR=/u/worksta/jmaxdev/releases
+
+# ***************************************************************************
+# Functions
+# ***************************************************************************
+
+# ---------------------------------------------------------------------------
 help ()
 {
     cat >&2 << HELP_EOF
@@ -17,85 +28,99 @@ Options:
 HELP_EOF
 }
 
-OPT="none"
-ARCH="none"
-TYPE="none"
-TAR="tar"
-TARFILE="none"
-ROOTDIR="none"
+# ---------------------------------------------------------------------------
+decrypt_options ()
+{
+    OPT="none"
+    ARCH="none"
+    TYPE="none"
+    TAR="tar"
+    TARFILE="none"
+    ROOTDIR="none"
 
-for ARG in $@
-do
-    if [ $OPT = "none" ]
+    for ARG in $@
+    do
+	if [ $OPT = "none" ]
+	then
+	    case $ARG in
+	    \-arch | \-tar | \-type )
+		OPT=$ARG ;;
+	    *)
+		help ;
+		exit 2 ;;
+	    esac
+	else
+	    case $OPT in
+	    \-arch )
+		ARCH=$ARG ;;
+	    \-type )
+		TYPE=$ARG ;;
+	    \-tar )
+		TAR=$ARG ;;
+	    esac
+	    OPT="none";
+	fi
+    done
+}
+
+# ---------------------------------------------------------------------------
+check_options ()
+{
+    if [ $ARCH = "none" ]
     then
-	case $ARG in
-	\-arch | \-tar | \-type )
-	    OPT=$ARG ;;
-	*)
-	    help ;
-	    exit 2 ;;
-	esac
-    else
-	case $OPT in
-	\-arch )
-	    ARCH=$ARG ;;
-	\-type )
-	    TYPE=$ARG ;;
-	\-tar )
-	    TAR=$ARG ;;
-	esac
-	OPT="none";
+	help
+	exit 2
     fi
-done
 
-# Check that we have what we need
-if [ $ARCH = "none" ]
-then
-    help
-    exit 2
-fi
+    if [ $TYPE = "none" ]
+    then
+	help
+	exit 2
+    fi
 
-if [ $TYPE = "none" ]
-then
-    help
-    exit 2
-fi
+    if [ \! -r VERSION ]
+    then
+	echo "Cannot find file VERSION (probably you're not in the correct directory ...)"
+	exit 1
+    fi
 
-if [ \! -r VERSION ]
-then
-    echo "Cannot find file VERSION (probably you're not in the correct directory ...)"
-    exit 1
-fi
+    #if $TAR --version | grep -s GNU >/dev/null 
+    #then
+    #    echo > /dev/null
+    #else
+    #    echo $TAR is not GNU tar. Cannot use it!
+    #    exit 2
+    #fi
+}
 
-#if $TAR --version | grep -s GNU >/dev/null 
-#then
-#    echo > /dev/null
-#else
-#    echo $TAR is not GNU tar. Cannot use it!
-#    exit 2
-#fi
+# ---------------------------------------------------------------------------
+compute_version_number ()
+{
+    MAJOR=`awk '$1=="MAJOR" { print $2; }' VERSION`
+    MINOR=`awk '$1=="MINOR" { print $2; }' VERSION`
+    PATCH_LEVEL=`awk '$1=="PATCH_LEVEL" { print $2; }' VERSION`
 
-#
-MAJOR=`awk '$1=="MAJOR" { print $2; }' VERSION`
-MINOR=`awk '$1=="MINOR" { print $2; }' VERSION`
-PATCH_LEVEL=`awk '$1=="PATCH_LEVEL" { print $2; }' VERSION`
+    VERSION=$MAJOR.$MINOR.$PATCH_LEVEL
+}
 
-VERSION=$MAJOR.$MINOR.$PATCH_LEVEL
+# ---------------------------------------------------------------------------
+create_dest_dir()
+{
+    if [ _${TMP}_ = __ ]
+    then
+	TMP=/tmp
+    fi
 
-# 
-if [ _${TMP}_ = __ ]
-then
-    TMP=/tmp
-fi
+    DEST_DIR=${TMP}/max-${VERSION}
+    if [ -d ${DEST_DIR} ]
+    then
+	/bin/rm -rf ${DEST_DIR}
+    fi
+    mkdir ${DEST_DIR}
+    chmod 755 ${DEST_DIR}
+}
 
-DEST_DIR=${TMP}/max-${VERSION}
-if [ -d ${DEST_DIR} ]
-then
-    /bin/rm -rf ${DEST_DIR}
-fi
-mkdir ${DEST_DIR}
-chmod 755 ${DEST_DIR}
-
+# ---------------------------------------------------------------------------
 # args: ARCH TYPE DIR DEST
 copy_files ()
 {
@@ -141,17 +166,45 @@ copy_files ()
     } < $3/distrib
 }
 
-echo Copying files
+# ---------------------------------------------------------------------------
+# Create the tar file
+create_tar ()
+{
+    TARDIR=${RELEASES_DIR}/${TYPE}/${ARCH}/${VERSION}
+    if [ ! -d ${TARDIR} ]
+    then
+	mkdir -p ${TARDIR}
+    fi
+    if [ ! -w ${TARDIR} ]
+    then
+	chmod u+w ${TARDIR}
+    fi
+
+    TARFILE=${TARDIR}/jmax.${TYPE}.${ARCH}.${VERSION}.tar.gz
+    if [ ! -w ${TARFILE} ]
+    then
+	chmod u+w ${TARFILE}
+    fi
+
+    echo "Creating tar file $TARFILE"
+    (cd ${TMP} ; tar cvf - max-${VERSION} ) | gzip -9 > $TARFILE
+    chmod 444 ${TARFILE}
+    chmod 555 ${TARDIR}
+}
+
+# ***************************************************************************
+# Beginning of script
+# ***************************************************************************
+
+decrypt_options $@
+
+check_options
+
+compute_version_number
+
+create_dest_dir
+
 copy_files $ARCH $TYPE . ${DEST_DIR}
 
-# Create the tar file
-TARDIR=/u/worksta/jmaxdev/releases/${TYPE}/${ARCH}/${VERSION}
-if [ ! -d ${TARDIR} ]
-then
-    mkdir -p ${TARDIR}
-fi
-TARFILE=${TARDIR}/jmax.${TYPE}.${ARCH}.${VERSION}.tar.gz
-echo "Creating tar file $TARFILE"
-(cd ${TMP} ; tar cvf - max-${VERSION} ) | gzip -9 > $TARFILE
-chmod 444 ${TARFILE}
-chmod 555 ${TARDIR}
+create_tar
+
